# Generated by Django 3.0.1 on 2020-01-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Prefferd_hospital',
            new_name='prefd_hospital',
        ),
        migrations.AddField(
            model_name='hospital',
            name='emergency_contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='bed_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='currently_free',
            field=models.IntegerField(default=0),
        ),
    ]
