# Generated by Django 3.0.1 on 2020-01-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Prefferd_hospital',
            new_name='prefd_hospital',
        ),
    ]
