# Generated by Django 3.0.1 on 2020-01-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200103_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='social_status',
            field=models.CharField(choices=[('SC', 'SC'), ('General', 'Gen'), ('ST', 'ST'), ('OBC', 'OBC')], default='Gen', max_length=8),
        ),
    ]
