# Generated by Django 2.2.6 on 2019-11-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('longi', models.CharField(max_length=250)),
                ('lati', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('bed_capacity', models.CharField(max_length=250)),
                ('currently_free', models.CharField(max_length=250)),
            ],
        ),
    ]
