# Generated by Django 2.2.6 on 2020-01-01 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list_hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('age', models.IntegerField(default=None)),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Others', 'O')], default='Male', max_length=2)),
                ('contact_no', models.IntegerField(unique=True)),
                ('social_status', models.CharField(choices=[('SC', 'SC'), ('Gen', 'Gen'), ('ST', 'ST'), ('OBC', 'OBC')], default='Gen', max_length=5)),
                ('user_id', models.CharField(max_length=100)),
                ('pass_word', models.CharField(max_length=25)),
                ('Prefferd_hospital', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='hospital_name',
            name='pass_word',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital_name',
            name='user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
